# Generated by Django 5.1.6 on 2025-02-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0002_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
